use update file

diff --git a/Dockerfile.redhat b/Dockerfile.redhat
--- a/Dockerfile.redhat
+++ b/Dockerfile.redhat
@@ -1,6 +1,5 @@
-#
+##
 # Copyright (c) 2020-2023 Intel Corporation
-#
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
 # You may obtain a copy of the License at
@@ -12,15 +11,14 @@
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License.
-#
 
-ARG BASE_IMAGE=registry.access.redhat.com/ubi9/ubi:9.5
+ARG BASE_IMAGE=registry.access.redhat.com/ubi9/ubi:9.6
 ARG BUILD_IMAGE=build
 ARG PKG_IMAGE=pkg
-ARG RELEASE_BASE_IMAGE=registry.access.redhat.com/ubi9/ubi-minimal:9.5
+ARG RELEASE_BASE_IMAGE=registry.access.redhat.com/ubi9-minimal:9.6
 
 FROM $BASE_IMAGE as base_build
-ARG BASE_IMAGE=registry.access.redhat.com/ubi9/ubi:9.5
+ARG BASE_IMAGE=registry.access.redhat.com/ubi9/ubi:9.6
 
 SHELL ["/bin/bash", "-xo", "pipefail", "-c"]
 
@@ -109,7 +107,6 @@ ARG JOBS=16
 ARG VERBOSE_LOGS=ON
 ARG LTO_ENABLE=ON
 
-
 # hadolint ignore=DL3041
 RUN dnf install -y https://mirror.stream.centos.org/9-stream/AppStream/x86_64/os/Packages/opencl-headers-3.0-6.20201007gitd65bcc5.el9.noarch.rpm && \
             dnf update -d6 -y && dnf install -d6 -y \
@@ -124,7 +121,7 @@ RUN dnf install -y https://mirror.stream.centos.org/9-stream/AppStream/x86_64/os
             unzip \
             vim \
             xz \
-            python3-devel \ 
+            python3-devel \
             libicu-devel && \
             dnf clean all
 
@@ -146,7 +143,6 @@ RUN python3 --version && python3 -m pip install "numpy<2.0.0" --no-cache-dir && 
     python3 --version && python3 -m pip install "Jinja2==3.1.6" "MarkupSafe==3.0.2" --no-cache-dir
 
 # Set up Bazel
-
 ENV BAZEL_VERSION 6.1.1
 WORKDIR /bazel
 RUN curl -H "User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36" -fSsL -O https://github.com/bazelbuild/bazel/releases/download/$BAZEL_VERSION/bazel-$BAZEL_VERSION-installer-linux-x86_64.sh && \
@@ -327,24 +323,47 @@ FROM $BUILD_IMAGE as capi-build
 # C api shared library
 ARG CAPI_FLAGS="--strip=always --config=mp_off_py_off --verbose_failures --//:distro=redhat --local_ram_resources=23552 --local_cpu_resources=16 --subcommands"
 ARG JOBS=16
-RUN bazel build --jobs $JOBS ${CAPI_FLAGS} //src:ovms_shared
+
+#RUN bazel build --jobs $JOBS ${CAPI_FLAGS} //src:ovms_shared
+
+RUN mkdir -p /tmp/bazel-output && \
+    bazel --output_base=/tmp/bazel-output \
+          build //src:ovms_shared && \
+    find /tmp/bazel-output -name libovms_shared.so && \
+    LIB_PATH=$(find /tmp/bazel-output -name libovms_shared.so | head -n1) && \
+    echo "Found built file: $LIB_PATH" && \
+    mkdir -p /ovms_release/lib && \
+    cp -v "$LIB_PATH" /ovms_release/lib/
+
 
 # C api app with bazel
 # hadolint ignore=DL3059
 RUN bazel build --jobs $JOBS ${CAPI_FLAGS} //src:capi_cpp_example
 
 # C-API benchmark app
-RUN bazel build --jobs=$JOBS ${CAPI_FLAGS} //src:capi_benchmark && ./bazel-bin/src/capi_benchmark --niter 2 --nstreams 1 --servable_name "dummy"
-# C-api C/C++ app with gcc
-COPY MakefileCapi /ovms/
-RUN make -f MakefileCapi cpp CAPI_FLAGS="${CAPI_FLAGS}" && \
-    make -f MakefileCapi c CAPI_FLAGS="${CAPI_FLAGS}"
+RUN bazel build --jobs=$JOBS ${CAPI_FLAGS} //src:capi_benchmark
+
+#workaround for debugging
+#RUN find /root/.cache/bazel/ -type f -name '*capi_benchmark*'
+
+#RUN ls -al /ovms_release/lib/
+
+RUN pwd && ls -al
+
+RUN bazel build --jobs=$JOBS ${CAPI_FLAGS} //src:capi_benchmark && \
+    echo "WORKDIR at build-time: $PWD" && \
+    bazel info bazel-bin && \
+    find $(bazel info bazel-bin)/src -type f -name capi_benchmark
 
 RUN mkdir -p /ovms_release/lib/ ; find /ovms/bazel-out/k8-*/bin -iname 'libovms_shared.so'  -exec cp -v {} /ovms_release/lib/ \;
+#RUN mkdir -p /ovms_release/lib/ ; find $(bazel info bazel-bin) -iname 'libovms_shared.so' -exec cp -v {} /ovms_release/lib/ \;
+
+#debuggig to find the correct lib file
+
 
 FROM $BUILD_IMAGE as pkg
 
-RUN mkdir /patchelf 
+RUN mkdir /patchelf
 WORKDIR /patchelf
 # hadolint ignore=DL3003
 RUN wget -q https://github.com/NixOS/patchelf/archive/0.10.tar.gz && \
@@ -356,6 +375,9 @@ ARG BASE_OS=redhat
 ARG ov_use_binary=0
 ARG FUZZER_BUILD=0
 ARG debug_bazel_flags="--strip=always --define MEDIAPIPE_DISABLE=0 --define PYTHON_DISABLE=0 --config=mp_on_py_on --verbose_failures --//:distro=redhat --local_ram_resources=23552 --local_cpu_resources=16"
+
+#workaround to debug
+RUN find / -name libovms_shared.so 2>/dev/null || echo "Not found"
 
 COPY --from=capi-build /ovms_release/lib/libovms_shared.so /ovms_release/lib/
 COPY create_package.sh /
